Really Brother?
```
  echo "Assets/JOELwindows7.meta" > metaList
  find Assets/JOELwindows7/ -name \*.meta >> metaList
  shell: /usr/bin/bash -e {0}
find: ‘Assets/JOELwindows7/’: No such file or directory
Error: Process completed with exit code 1.
```

what do you expect from `project-folder`?